### ISSUE TITLE
Decide which subjects to write on

### ISSUE THREAD

**Issue by Karla-Isabel-Sandoval** [CocoaGems/SummerofCocoaPods#1]
We need to decide which subjects we are interested in covering so that there is less repetition.
 Guideline:
"A little background on what RGSOC, how you first met the team, how you found a schedule with mentors, then what are the most important bits of work you did" -Orta

[ ] A little background on RGSoC - Emma

[ ] How we first me the Team - Karla 

[ ] How we scheduled with mentors and coaches in different Time Zones - K & E

[ ] The most important bits of work that we did - K & E

**Comment by Karla-Isabel-Sandoval** [comment]
little background on what RGSOC, how you first met the team, how you found a schedule with mentors, then what are the most important bits of work you did

**Comment by emkosz** [comment]
More posible topics: 
What went well
Suggestions for other teams
